### PR TITLE
Implement i18n

### PR DESCRIPTION
**Pull request by Tenebrosful**
#35

### CODE REVIEW

**Comment by Tenebrosful** [comment]
# Know bug
Commands descriptions and "Connected to Discord" strings aren't translated because SMAPI loads game lang after Entry (see https://github.com/Pathoschild/SMAPI/issues/938)

**Comment by RuiNtD** [comment]
I'm probably going to be making some changes to the code if I introduce i18n, like changing "1 tag unavailable" to "1 tag(s) unavailable," since I know plurals complicate i18n in some languages. Also, I'm going to change "DiscordRP is not supported on Android. Aborting mod initialization." to "Discord Rich Presence is untested on this platform and may not work." This would show up in console and on the title screen and I would also add a config option to "Disable Unsupported Platform Warning".

**Comment by Tenebrosful** [comment]
> I'm probably going to be making some changes to the code if I introduce i18n, like changing "1 tag unavailable" to "1 tag(s) unavailable," since I know plurals complicate i18n in some languages. ~Also, I'm going to change "DiscordRP is not supported on Android. Aborting mod initialization." to "Discord Rich Presence is untested on this platform and may not work." This would show up in console and on the title screen and I would also add a config option to "Disable Untested Platform Warning".~
> 
> Decided to remove this warning altogether.

Yeah, i tried to transform current code to i18n even with plurals, most of job is done so changes shouldn't be hard

**Comment by RuiNtD** [comment]
@Tenebrosful Can you do one quick pass to make sure everything French is translated correctly? I did change around some of the keys. Once you can confirm it's good, I'll go ahead and merge. Thanks for the help!

Also, can you confirm if https://github.com/Pathoschild/SMAPI/issues/938 is still an issue after switching to the strongly-typed API?

**Comment by Tenebrosful** [comment]
Legit for me, but yeah still an issue but i don't think it can really be resolve by ourself

**Pull request merged**
